"""Editor-facing wording for what a draft review did and did not check.

These sentences were built in the use case that decides which checks apply,
which fixed the report to one language and put copywriting inside application
logic. They live here for the same reason recommendation wording does.

Two rules govern the language. A check that could not run is stated with its
reason and never as something missing: an editor reads "not yet", not "you
forgot". And the reason is the real one -- waiting for the page to exist,
having no formatting to read, or having nothing chosen to compare against are
three different situations and are never worded alike.
"""

from typing import Dict

from aether.application.analysis.build_draft_review import (
    DraftCheck,
    UnavailableCheck,
)

PERFORMED_TEXT: Dict[DraftCheck, str] = {
    DraftCheck.PARAGRAPH_STRUCTURE: "Paragraph structure",
    DraftCheck.HEADING_STRUCTURE: "Heading structure",
    DraftCheck.REPEATED_TEXT: "Text repeated in your other articles",
}

PERFORMED_TEXT_TR: Dict[DraftCheck, str] = {
    DraftCheck.PARAGRAPH_STRUCTURE: "Paragraf yapısı",
    DraftCheck.HEADING_STRUCTURE: "Başlık yapısı",
    DraftCheck.REPEATED_TEXT: "Diğer makalelerinizde tekrarlanan metin",
}

UNAVAILABLE_TEXT: Dict[UnavailableCheck, str] = {
    UnavailableCheck.PUBLISHED_METADATA: (
        "Publication date, author, and description set when the article is published"
    ),
    UnavailableCheck.DECLARED_CONSISTENCY: (
        "Whether the page declares one consistent title and description; this "
        "requires the published page"
    ),
    UnavailableCheck.STRUCTURED_DATA: (
        "Schema.org structured data generated by the site template"
    ),
    UnavailableCheck.HEADING_STRUCTURE_WITHOUT_MARKUP: (
        "Heading structure because the pasted draft contains no formatting"
    ),
    UnavailableCheck.REPEATED_TEXT_NO_PUBLISHER: (
        "Text repeated in other articles because no publisher was selected"
    ),
    UnavailableCheck.REPEATED_TEXT_NO_ARTICLES: (
        "Text repeated in other articles because no articles from this publisher "
        "have been analyzed yet"
    ),
}

UNAVAILABLE_TEXT_TR: Dict[UnavailableCheck, str] = {
    UnavailableCheck.PUBLISHED_METADATA: (
        "Makale yayımlandığında belirlenen yayın tarihi, yazar ve açıklama"
    ),
    UnavailableCheck.DECLARED_CONSISTENCY: (
        "Sayfanın tutarlı bir başlık ve açıklama bildirip bildirmediği; bunun "
        "için yayımlanmış sayfa gerekir"
    ),
    UnavailableCheck.STRUCTURED_DATA: (
        "Site şablonunun oluşturduğu Schema.org yapılandırılmış verisi"
    ),
    UnavailableCheck.HEADING_STRUCTURE_WITHOUT_MARKUP: (
        "Yapıştırılan taslak biçimlendirme içermediği için başlık yapısı"
    ),
    UnavailableCheck.REPEATED_TEXT_NO_PUBLISHER: (
        "Yayıncı seçilmediği için diğer makalelerde tekrarlanan metin"
    ),
    UnavailableCheck.REPEATED_TEXT_NO_ARTICLES: (
        "Bu yayıncıya ait henüz makale analiz edilmediği için diğer "
        "makalelerde tekrarlanan metin"
    ),
}


def performed_check_text(check: DraftCheck, language: str = "en") -> str:
    return (PERFORMED_TEXT_TR if language == "tr" else PERFORMED_TEXT)[check]


def unavailable_check_text(check: UnavailableCheck, language: str = "en") -> str:
    return (UNAVAILABLE_TEXT_TR if language == "tr" else UNAVAILABLE_TEXT)[check]
